# Generated by Django 2.0 on 2018-01-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gifts.Person'),
            preserve_default=False,
        ),
    ]
