# Generated by Django 2.0 on 2018-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_auto_20180112_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=50),
            preserve_default=False,
        ),
    ]
